name: 'Test build'
run-name: '🗃️ Test build: ${{ github.event.head_commit.message || github.event.pull_request.title }}'

on:
  push:
    branches:
      - main
      - release
      - meteor-v3
      - v3
  pull_request:
    branches:
      - main
      - release
      - v3

jobs:
  vue:
    name: 'Vue'
    uses: ./.github/workflows/_reuse_.build.yml
    with:
      appBasename: 'vue'

  svelte:
    name: 'Svelte'
    uses: ./.github/workflows/_reuse_.build.yml
    with:
      appBasename: 'svelte'

  react:
    name: 'React'
    uses: ./.github/workflows/_reuse_.build.yml
    with:
      appBasename: 'react'

  solid:
    name: 'Solid'
    uses: ./.github/workflows/_reuse_.build.yml
    with:
      appBasename: 'solid'

  vue-meteor-v3:
    name: 'Meteor v3'
    uses: ./.github/workflows/_reuse_.build.yml
    with:
      appBasename: 'meteor-v3-vue'

  vue-ssr:
    name: 'Vue + SSR'
    uses: ./.github/workflows/_reuse_.build.yml
    with:
      appBasename: 'vue-ssr'